// This file has been generated by Specta. Do not edit this file manually.
/**
 *  A GeoJSON bounding box (RFC 7946 §5): a flat array of `2*n` numbers, either
 *  4 (2D, `[west, south, east, north]`) or 6 (3D, with min/max elevation).
 * 
 *  Modeled as a tuple union to match `@types/geojson`'s
 *  `BBox = [number, number, number, number] | [number, …×6]`, so it is
 *  assignable **to and from** the native type (a plain `number[]` is not).
 */
export type Bbox = 
/**  2D bounding box: `[west, south, east, north]`. */
[number, number, number, number] | 
/**  3D bounding box: `[west, south, min-elev, east, north, max-elev]`. */
[number, number, number, number, number, number];

/**
 *  A GeoJSON Feature: a geometry `G` and its associated `properties` `P`
 *  (RFC 7946 §3.2).
 */
export type Feature<G, P> = {
	type: FeatureType,
	geometry: G,
	properties: P,
	id?: Id,
	bbox?: Bbox,
};

/**  A GeoJSON FeatureCollection: a list of `Feature`s (RFC 7946 §3.3). */
export type FeatureCollection<G, P> = {
	type: FeatureCollectionType,
	features: (Feature<G, P>)[],
	bbox?: Bbox,
};

/**  The `"FeatureCollection"` value of a collection's `type` member. */
export type FeatureCollectionType = "FeatureCollection";

/**  The `"Feature"` value of a Feature's `type` member. */
export type FeatureType = "Feature";

/**
 *  The GeoJSON geometry union (RFC 7946 §3.1): mirrors `@types/geojson`'s
 *  `Geometry`. Untagged at the serde layer; each member's own `"type"` literal
 *  disambiguates, so it round-trips losslessly and exports to the TS union.
 */
export type Geometry = Point | MultiPoint | LineString | MultiLineString | Polygon | MultiPolygon | GeometryCollection;

/**  A GeoJSON GeometryCollection (RFC 7946 §3.1.8): a list of geometries. */
export type GeometryCollection = {
	type: GeometryCollectionType,
	geometries: Geometry[],
	bbox?: Bbox,
};

/**  The `"GeometryCollection"` value of a [`GeometryCollection`]'s `type` member. */
export type GeometryCollectionType = "GeometryCollection";

/**  A GeoJSON Feature `id` — a string or a number (RFC 7946 §3.2). */
export type Id = string | number;

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type LineString = {
	type: LineStringType,
	coordinates: number[][],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type LineStringType = "LineString";

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type MultiLineString = {
	type: MultiLineStringType,
	coordinates: number[][][],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type MultiLineStringType = "MultiLineString";

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type MultiPoint = {
	type: MultiPointType,
	coordinates: number[][],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type MultiPointType = "MultiPoint";

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type MultiPolygon = {
	type: MultiPolygonType,
	coordinates: number[][][][],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type MultiPolygonType = "MultiPolygon";

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type Point = {
	type: PointType,
	coordinates: number[],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type PointType = "Point";

/**
 *  A GeoJSON geometry object (RFC 7946 §3.1), matching the native
 *  `@types/geojson` interface of the same name.
 */
export type Polygon = {
	type: PolygonType,
	coordinates: number[][][],
	bbox?: Bbox,
};

/**
 *  The `"type"` member of a single geometry kind — a string literal,
 *  which is what makes the type assignable to the native geometry.
 */
export type PolygonType = "Polygon";
